BASE_URL = 'https://api.school-app.dev.cleveroad.com/api/v1'
BASE_HEADERS = {'content-type': 'application/json'}
SUCCESS_STATUS_CODE = 200
BAD_REQUEST_STATUS_CODE = 400
EXISTING_ELEMENT_ERROR_STATUS_CODE = 422
UNAUTHORIZED_STATUS_CODE = 401
FORBIDDEN_STATUS_CODE = 403
NOT_FOUND_STATUS_CODE = 404




